### ISSUE TITLE
Incorrect formula for Lorentzian

### ISSUE THREAD

**Issue by celinedurniak** [arm61/trad_ml_methods#1]
In the final html document at [https://mccluskey.scot/trad_ml_methods/some_stats.html](https://mccluskey.scot/trad_ml_methods/some_stats.html) for 
<img width="248" alt="Screenshot 2021-02-11 at 15 14 32" src="https://user-images.githubusercontent.com/7889724/107649398-b5b23900-6c7d-11eb-9777-36a4f8c1d256.png">
 parentheses are missing around (x-x0)/gamma. And only this last term should be squared. 

The code is correct.

See [https://mathworld.wolfram.com/LorentzianFunction.html](https://mathworld.wolfram.com/LorentzianFunction.html)

**Comment by arm61** [comment]
fixed in https://github.com/arm61/trad_ml_methods/commit/d3bfcc59244902824ea93d0028b38ea207dd7879
