### ISSUE TITLE
Typos in "Bayes' theorem" section

### ISSUE THREAD

**Issue by celinedurniak** [arm61/trad_ml_methods#12]
At [https://mccluskey.scot/trad_ml_methods/bayes_theorem.html](https://mccluskey.scot/trad_ml_methods/bayes_theorem.html)

> is the prior **porbability** for the model, 

I do not understand this sentence:

> To fully quantify the evidence it is necessary that sampling to evaluate this integral,

**Comment by arm61** [comment]
fixed in a16c52c
