### ISSUE TITLE
Typos in "How many layers?" section

### ISSUE THREAD

**Issue by celinedurniak** [arm61/trad_ml_methods#14]
At [https://mccluskey.scot/trad_ml_methods/bayes_exercise.html](https://mccluskey.scot/trad_ml_methods/bayes_exercise.html)

**memebranes**

obfusigated (??)

**seperate** piece of Python code (this is available **here** (Should this link to an external resource?). We can import the fitting objective for each of the layers as shown below.

Typically this roughness **values** is ...

**Comment by arm61** [comment]
fixed in 4cb32b5
