### ISSUE TITLE
Minor comments to teaching material

### ISSUE THREAD

**Issue by wpotrzebowski** [arm61/trad_ml_methods#15]
Well done. Good as it is and here are some minor suggestions
•	In the likelihood equation you can also use Y vector or lower case for d data point.
•	“likelihood appears to be Gaussian in nature”  - not exactly sure what do you mean about this? Isn’t usually approximation for QENS/scattering data?
•	You can probably mention that k-means clustering include all (also outlires). 
•	Typo in covarience_type 
•	If you want to use example from scattering world, PCA (or more precisely SVD) is routinely used in Small Angle Scattering for deconvoluting signal from mixtures (e.g. mixtures of oligomers). One can probably also mention methods like MCR-ALS that doesn’t impose orthogonality to extracted components. 
•	Extra “_” in n_components_ 

I haven't read Bayesian part yet - will submit separate issue if there is anything to comment on. Also I haven't focused on the code but it seems to do what is supposed to do:)

**Comment by arm61** [comment]
fixed in 6b1f21e
