### ISSUE TITLE
Comments to Bayesian part

### ISSUE THREAD

**Issue by wpotrzebowski** [arm61/trad_ml_methods#16]
1. I think this part may be little bit difficult to follow for someone not familiar with Bayesian statistics. You may consider adding some example about likelihood and prior and effects on determined parameters after you introduce Bayes theorem, so that students can gain some intuition. 
2. There is some inconsistency of using word _evidence_. Some use in the context you used while others refer to _model evidence_ for normalization constant. I once ended up in the longish discussion about it and then it turned out that we are talking about different _evidence_.  
2. How many layers exercise - missing image bayes_exercise_2._0.png

**Comment by arm61** [comment]
I have dealt with the first point in 2940969 with a link to a YouTube video I like. I will cover the differences between evidence in the lecture component
