### ISSUE TITLE
What is the source for the cartoon in "some statistics"

### ISSUE THREAD

**Issue by celinedurniak** [arm61/trad_ml_methods#3]
Link to page I am talking about: [https://mccluskey.scot/trad_ml_methods/some_stats.html](https://mccluskey.scot/trad_ml_methods/some_stats.html )

**Comment by arm61** [comment]
fixed in https://github.com/arm61/trad_ml_methods/commit/d3bfcc59244902824ea93d0028b38ea207dd7879
