### ISSUE TITLE
name 'X' is not defined in "decision trees"

### ISSUE THREAD

**Issue by celinedurniak** [arm61/trad_ml_methods#4]
At [https://mccluskey.scot/trad_ml_methods/decision_trees.html](https://mccluskey.scot/trad_ml_methods/decision_trees.html), the first piece of Python code

```
plt.scatter(X[:, 0], X[:, 1], c=y, s=50)
plt.show()
```
generates the error mentioned in the title of the issue.

**Comment by arm61** [comment]
Oops! Fixed in https://github.com/arm61/trad_ml_methods/commit/d3bfcc59244902824ea93d0028b38ea207dd7879
