### ISSUE TITLE
Typos in "Clustering" section

### ISSUE THREAD

**Issue by celinedurniak** [arm61/trad_ml_methods#5]
At [https://mccluskey.scot/trad_ml_methods/clustering.html](https://mccluskey.scot/trad_ml_methods/clustering.html)

> When there is a large number of datapoints, it is often useful **for be** able to group the data together into subclasses. For this, the traditional machine learning approach is a **from** of unsupervised learning known as clustering.  Clustering methods aim to determine the **optimial** division of groups of data points; facilitating the labeling of these groups... to look at the more flexible Gaussian mixture models. Finally, you will be given the chance to apply these clustering approaches to the **identifation** of space groups in X-ray diffraction data.

**Comment by arm61** [comment]
fixed in 9be1cc6
