### ISSUE TITLE
Typos in "k-Means Clustering"

### ISSUE THREAD

**Issue by celinedurniak** [arm61/trad_ml_methods#6]
At [https://mccluskey.scot/trad_ml_methods/k_means.html](https://mccluskey.scot/trad_ml_methods/k_means.html)

k-means clustering is an algorithm that searches for a given **numebr** of clusters within some unlabeled multidimensional dataset. The optimal clustering is found as follow:

- The “cluster centre” is the **artihmetic** mean of all of the points belonging to the cluster.

Each **repeatition** will always result in **an** better estimate of the cluster characteristics.

The globally optimal result may not be achieved: As is the **cause** with all optimisations, although the result is improving,

**Comment by arm61** [comment]
fixed in 33cae33
