### ISSUE TITLE
Typos in Dimensionality reduction

### ISSUE THREAD

**Issue by celinedurniak** [arm61/trad_ml_methods#8]
At [https://mccluskey.scot/trad_ml_methods/dimensionality_reduction.html](https://mccluskey.scot/trad_ml_methods/dimensionality_reduction.html)

...**out** data and allow us to drill down into these...

First, we will introduce some background of **how**(to be removed??) this method before looking in detail ...

**Comment by arm61** [comment]
fix in 78c31db
