### ISSUE TITLE
Typos in "Principal Component Analysis" section

### ISSUE THREAD

**Issue by celinedurniak** [arm61/trad_ml_methods#9]
At [https://mccluskey.scot/trad_ml_methods/pca.html](https://mccluskey.scot/trad_ml_methods/pca.html)
We can **visiualise** these as vectors over our data, where the components are the vector direction and the explained variance is the squared-length.

These vectors are the data’s principal axes and **then** length is 

 (it is a measure of the **vairance** when the data is projected onto that axis)

**Comment by arm61** [comment]
fixed in e2cfcb5
